sudo: required

language: python

env:
  - BUILD_TARGET=sketch
  - BUILD_TARGET=tests

install:
  - sudo sh prepare-$BUILD_TARGET.sh
  - sh init-$BUILD_TARGET.sh

script:
  - sudo rm ~/.platformio -R
  - sh increment-version.sh
  - sh inject-version.sh
  - sh build-$BUILD_TARGET.sh
